FROM node:22-alpine as build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npm run build

FROM alpine:latest
COPY --from=build /app/dist /app/dist

CMD ["tail", "-f", "/dev/null"]