FROM node:22-alpine as build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

FROM alpine:latest

WORKDIR /app

COPY --from=build /app/dist /app/dist_internal

CMD sh -c "cp -rp /app/dist_internal/. /app/dist/ && echo 'Frontend build updated in volume' && tail -f /dev/null"
